# Generated by Django 5.0.6 on 2024-07-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_name', models.CharField(max_length=100)),
                ('re_description', models.TextField(max_length=1000)),
                ('re_price', models.IntegerField()),
                ('re_images', models.ImageField(upload_to='receipe')),
            ],
        ),
    ]
